/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_dump_DumpJni */

#ifndef _Included_com_example_dump_DumpJni
#define _Included_com_example_dump_DumpJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_dump_DumpJni
 * Method:    dump
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_dump_DumpJni_dump
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
